ALTER TABLE users
    ADD COLUMN display_name VARCHAR(100),
    ADD COLUMN phone VARCHAR(20),
    ADD COLUMN enabled BOOLEAN DEFAULT TRUE NOT NULL,
    ADD COLUMN last_login TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
